INCLUDE_PATH    := ./ ../external/SuiteSparse/include/ ../common/
SOURCE_PATH     := ./ ../common/
DEPENDENCY_PATH := dep
OBJECT_PATH     := obj

EXTERNAL_LIBS := $(wildcard ../external/SuiteSparse/lib/*)
LDLIBS := -lm -lpthread


CFLAGS += -O3

include ../makefile.mk
